"""contracts package
Exportación centralizada de contratos tipados inmutables Pydantic V2 para Ultrarentable V2.
"""

from contracts.canonical_strategy import (
    CanonicalStrategy,
    StrategyLifecycleStatus,
    ExecutionTrack,
    TargetInstrument,
    RuleTree,
    RuleCondition,
    IndicatorSpec,
    ExitModel,
    SizingAndRisk,
    SessionWindow,
    ProvenanceMetadata,
)
from contracts.validation_contracts import (
    ValidationTrack,
    BalaState,
    BalaExecutionRecord,
    BalaHarvestEvent,
    FondeoValidationCriteria,
    FondeoValidationResult,
    UltraValidationCriteria,
    UltraValidationResult,
    EvidenceGateDecision,
)
from contracts.backtest import (
    EngineType,
    BarData,
    DatasetSnapshot,
    TradeLog,
    EquityPoint,
    BacktestRequest,
    BacktestResult,
)
from contracts.portfolio import (
    AllocationMethod,
    AssetWeight,
    PortfolioRequest,
    PortfolioAllocation,
    IsolatedBullet,
    BulletLayer,
    VaultRatchetConfig,
    PropChallengeConfig,
)

__all__ = [
    "CanonicalStrategy",
    "StrategyLifecycleStatus",
    "ExecutionTrack",
    "TargetInstrument",
    "RuleTree",
    "RuleCondition",
    "IndicatorSpec",
    "ExitModel",
    "SizingAndRisk",
    "SessionWindow",
    "ProvenanceMetadata",
    "ValidationTrack",
    "BalaState",
    "BalaExecutionRecord",
    "BalaHarvestEvent",
    "FondeoValidationCriteria",
    "FondeoValidationResult",
    "UltraValidationCriteria",
    "UltraValidationResult",
    "EvidenceGateDecision",
    "EngineType",
    "BarData",
    "DatasetSnapshot",
    "TradeLog",
    "EquityPoint",
    "BacktestRequest",
    "BacktestResult",
    "AllocationMethod",
    "AssetWeight",
    "PortfolioRequest",
    "PortfolioAllocation",
    "IsolatedBullet",
    "BulletLayer",
    "VaultRatchetConfig",
    "PropChallengeConfig",
]
