"""contracts/gate_directory.py
Directorio Canónico de los 11 Quality Gates de Ultrarentable.
Regenerado con paridad exacta a los umbrales de la suite B (D5 / motor 5.17.0).
"""

from typing import Any, Dict, List

GATES_DIRECTORY: List[Dict[str, Any]] = [
    {
        "id": 1,
        "slug": "gate-1-data-ingest",
        "name": "Integridad de Datos OHLCV",
        "description": "Verificación de continuidad temporal, cero velas corruptas, cero desorden y gaps <= 2% según timeframe.",
        "default_params": {
            "min_bars_1d": 50,
            "min_bars_4h": 150,
            "min_bars_1h": 200,
            "min_bars_otros": 300,
            "max_gap_frac": 0.02,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_01.py",
    },
    {
        "id": 2,
        "slug": "gate-2-cost-backtest",
        "name": "Backtest con Comisiones y Slippage",
        "description": "Deducción de comisiones institucionales y slippage por mercado con exigencia de PF neto >= 1.10 y PnL neto positivo.",
        "default_params": {
            "min_trades": 10,
            "min_net_pf": 1.10,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_02.py",
    },
    {
        "id": 3,
        "slug": "gate-3-trade-significance",
        "name": "Significancia Estadística de Trades",
        "description": "Mínimo de trades IS/OOS por ruta y límite estricto a la dependencia de outliers (top-2 trades).",
        "default_params": {
            "min_is_ultra": 15,
            "min_is_fondeo": 30,
            "min_oos_ultra": 10,
            "min_oos_fondeo": 20,
            "max_outlier_ratio_ultra": 85.0,
            "max_outlier_ratio_fondeo": 50.0,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_03.py",
    },
    {
        "id": 4,
        "slug": "gate-4-walk-forward",
        "name": "Walk-Forward Optimization (WFO)",
        "description": "Evaluación rodante Rolling WFO sobre datos Pre-OOS exigiendo WFE media >= 0.40 y consistencia OOS >= 40%.",
        "default_params": {
            "min_trades": 20,
            "min_avg_wfe": 0.40,
            "min_consistency_pct": 40.0,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_04.py",
    },
    {
        "id": 5,
        "slug": "gate-5-monte-carlo",
        "name": "Remuestreo Monte Carlo (0% Ruina)",
        "description": "Remuestreo bootstrap sobre trades OOS asegurando ruina <= 0.5% (Fondeo) o 5.0% (Ultra) y DD 95% dentro de límites.",
        "default_params": {
            "min_trades": 10,
            "ruin_drawdown_pct_ultra": 85.0,
            "ruin_drawdown_pct_fondeo": 4.5,
            "max_dd95_pct_ultra": 80.0,
            "max_dd95_pct_fondeo": 4.0,
            "rng_seed": 42,
            "max_ruin_prob_pct_ultra": 5.0,
            "max_ruin_prob_pct_fondeo": 0.5,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_05.py",
    },
    {
        "id": 6,
        "slug": "gate-6-stress-slippage",
        "name": "Estrés de Fricción 3x",
        "description": "Modelado de fricción y slippage en 4 escenarios progresivos (+1σ a +3σ) exigiendo supervivencia multiescenario.",
        "default_params": {
            "min_trades": 5,
            "min_survival_pf_ultra": 1.00,
            "min_survival_pf_fondeo": 1.05,
            "min_required_scenarios_ultra": 1,
            "min_required_scenarios_fondeo": 2,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_06.py",
    },
    {
        "id": 7,
        "slug": "gate-7-regime-coverage",
        "name": "Cobertura Multirégimen",
        "description": "Clasificación objetiva en 4 regímenes y mapeo temporal real de trades exigiendo actividad en >= 2 regímenes y PnL positivo.",
        "default_params": {
            "min_candles": 50,
            "min_active_regimes": 2,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_07.py",
    },
    {
        "id": 8,
        "slug": "gate-8-dsr-ratio",
        "name": "Deflated Sharpe Ratio (DSR)",
        "description": "Ajuste analítico del ratio de Sharpe penalizando el sesgo de selección según número real de trials explorados (DSR prob >= 50%).",
        "default_params": {
            "min_trades": 10,
            "min_dsr_prob": 0.50,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_08.py",
    },
    {
        "id": 9,
        "slug": "gate-9-novelty-antifit",
        "name": "Novedad y Anti-Overfitting",
        "description": "Ratio de grados de libertad efectivo (DoF >= 10/15) y re-backtesting físico de vecindario paramétrico perturbado (estabilidad >= 50%/60%).",
        "default_params": {
            "min_dof_ultra": 10.0,
            "min_dof_fondeo": 15.0,
            "min_stability_pct_ultra": 50.0,
            "min_stability_pct_fondeo": 60.0,
            "max_params": 8,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_09.py",
    },
    {
        "id": 10,
        "slug": "gate-10-debate-agentes",
        "name": "Consenso de Debate Multi-Agente",
        "description": "Auditoría de 5 roles analíticos independientes con veto estricto de riesgo y consenso ponderado >= 40.0.",
        "default_params": {
            "max_dd_limit_ultra": 30.0,
            "max_dd_limit_fondeo": 4.0,
            "min_consensus_score": 40.0,
            "min_pf_oos": 1.05,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_10.py",
    },
    {
        "id": 11,
        "slug": "gate-11-nautilus-event",
        "name": "Reconciliación de Eventos NautilusCore",
        "description": "Validación cruzada independiente modelando apalancamiento dinámico, margen, financiación y distancia mínima a liquidación.",
        "default_params": {
            "min_trades": 5,
            "min_dist_liquidation_pct_ultra": 2.0,
            "min_dist_liquidation_pct_fondeo": 20.0,
        },
        "version": "1.0.0",
        "module": "services/validation/registry/gates/gate_11.py",
    },
]
