"""
seed_prop_firms.py — Base de Datos Canónica y Verificada de FIRMAS DE FONDEO DE FUTUROS CME.
Datos 100% reales con jerarquía multidimensional: Empresa -> Tipo de Programa -> Tamaño de Cuenta.
Diferenciación estricta entre Reglas de Examen (Challenge) y Reglas de Cuenta Fondeada (Master/Live).
"""

from __future__ import annotations
from typing import List, Dict, Any

PROP_FIRMS_CATALOG: List[Dict[str, Any]] = [
    # =========================================================================
    # 1. MY FUNDED FUTURES (MFFU) — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "mffu_rapid_25k",
        "name": "MyFundedFutures Rapid 25K ($0 Activación)",
        "provider_name": "My Funded Futures",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / TradingView",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 25000.0,
        "program_type": "Rapid",
        "account_tier": "25K",
        "target_usd": 1500.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 1500.0,
        "max_trailing_dd_pct": 6.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 40.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 49.0,
        "regular_price_usd": 49.0,
        "promo_price_usd": 24.50,
        "discount_code": "300K",
        "discount_pct": 50.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Día 1 / On-Demand",
        "payout_buffer_usd": 1600.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "2 Minis / 20 Micros",
        "trust_score": 93,
        "stage_type": "EVALUATION",
        "source_url": "https://myfundedfutures.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de los primeros $10,000 netos. $0 activación. El trailing se congela en $25,100 al fondear."
    },
    {
        "provider_id": "mffu_rapid_50k",
        "name": "MyFundedFutures Rapid 50K ($0 Activación)",
        "provider_name": "My Funded Futures",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / TradingView",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Rapid",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 40.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 79.0,
        "regular_price_usd": 79.0,
        "promo_price_usd": 39.50,
        "discount_code": "300K",
        "discount_pct": 50.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Día 1 / On-Demand",
        "payout_buffer_usd": 2100.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "5 Minis / 50 Micros",
        "trust_score": 94,
        "stage_type": "EVALUATION",
        "source_url": "https://myfundedfutures.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $10,000 netos. Cero cuota de activación. Trailing DD congela en $50,100."
    },
    {
        "provider_id": "mffu_rapid_100k",
        "name": "MyFundedFutures Rapid 100K ($0 Activación)",
        "provider_name": "My Funded Futures",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / TradingView",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 100000.0,
        "program_type": "Rapid",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 40.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 159.0,
        "regular_price_usd": 159.0,
        "promo_price_usd": 79.50,
        "discount_code": "300K",
        "discount_pct": 50.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Día 1 / On-Demand",
        "payout_buffer_usd": 3100.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "10 Minis / 100 Micros",
        "trust_score": 94,
        "stage_type": "EVALUATION",
        "source_url": "https://myfundedfutures.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $10k. Sin activación. Payouts casi instantáneos."
    },
    {
        "provider_id": "mffu_starter_50k",
        "name": "MyFundedFutures Starter 50K (Low Subscription)",
        "provider_name": "My Funded Futures",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY",
        "account_size": 50000.0,
        "program_type": "Starter",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 50.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 49.0,
        "regular_price_usd": 49.0,
        "promo_price_usd": 24.50,
        "discount_code": "300K",
        "discount_pct": 50.0,
        "activation_fee_usd": 149.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 2100.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "5 Minis",
        "trust_score": 91,
        "stage_type": "EVALUATION",
        "source_url": "https://myfundedfutures.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Plan económico de examen; cuota de activación de $149 al pasar."
    },

    # =========================================================================
    # 2. TOPSTEP — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "topstep_combine_50k",
        "name": "Topstep Combine 50K (TopstepX / Tradovate)",
        "provider_name": "Topstep",
        "market_type": "FUTURES",
        "platform": "TopstepX / Tradovate / NinjaTrader",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Trading Combine",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 1000.0,
        "daily_loss_limit_pct": 2.0,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 50.0,
        "min_trading_days": 2,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED_WITH_CONDITIONS",
        "monthly_cost_usd": 49.0,
        "regular_price_usd": 49.0,
        "promo_price_usd": 49.0,
        "discount_code": None,
        "discount_pct": 0.0,
        "activation_fee_usd": 149.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Diario (5d ganadores > $200)",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "5 Minis / 50 Micros",
        "trust_score": 96,
        "stage_type": "EVALUATION",
        "source_url": "https://help.topstep.com/en/articles/8284197-account-combine-parameters",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Firma #1 en solvencia y volumen. 100% de primeros $10k. Sin comisiones en TopstepX. Prohibido VPS comercial/proxy."
    },
    {
        "provider_id": "topstep_combine_100k",
        "name": "Topstep Combine 100K",
        "provider_name": "Topstep",
        "market_type": "FUTURES",
        "platform": "TopstepX / Tradovate / NinjaTrader",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 100000.0,
        "program_type": "Trading Combine",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 2000.0,
        "daily_loss_limit_pct": 2.0,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 50.0,
        "min_trading_days": 2,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED_WITH_CONDITIONS",
        "monthly_cost_usd": 99.0,
        "regular_price_usd": 99.0,
        "promo_price_usd": 99.0,
        "discount_code": None,
        "discount_pct": 0.0,
        "activation_fee_usd": 149.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Diario (5d ganadores > $200)",
        "payout_buffer_usd": 3000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "10 Minis / 100 Micros",
        "trust_score": 96,
        "stage_type": "EVALUATION",
        "source_url": "https://topstep.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $10k. Pagos procesados en 24h vía Deel/Banco."
    },
    {
        "provider_id": "topstep_combine_150k",
        "name": "Topstep Combine 150K",
        "provider_name": "Topstep",
        "market_type": "FUTURES",
        "platform": "TopstepX / Tradovate / NinjaTrader",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 150000.0,
        "program_type": "Trading Combine",
        "account_tier": "150K",
        "target_usd": 9000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 3000.0,
        "daily_loss_limit_pct": 2.0,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 4500.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 50.0,
        "min_trading_days": 2,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED_WITH_CONDITIONS",
        "monthly_cost_usd": 149.0,
        "regular_price_usd": 149.0,
        "promo_price_usd": 149.0,
        "discount_code": None,
        "discount_pct": 0.0,
        "activation_fee_usd": 149.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Diario (5d ganadores > $200)",
        "payout_buffer_usd": 4500.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "15 Minis / 150 Micros",
        "trust_score": 96,
        "stage_type": "EVALUATION",
        "source_url": "https://topstep.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Capacidad de hasta 15 contratos minis para escalado."
    },

    # =========================================================================
    # 3. TRADEIFY — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "tradeify_growth_25k",
        "name": "Tradeify Growth 25K ($0 Activación / EOD)",
        "provider_name": "Tradeify",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / TradingView",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 25000.0,
        "program_type": "Growth",
        "account_tier": "25K",
        "target_usd": 1500.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 1500.0,
        "max_trailing_dd_pct": 6.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 59.0,
        "regular_price_usd": 59.0,
        "promo_price_usd": 35.40,
        "discount_code": "TNT",
        "discount_pct": 40.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "24-48h On-Demand",
        "payout_buffer_usd": 1600.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "3 Minis / 30 Micros",
        "trust_score": 92,
        "stage_type": "EVALUATION",
        "source_url": "https://tradeify.co/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Sin cuota de activación. Trailing EOD. Retiros procesados en 24-48h."
    },
    {
        "provider_id": "tradeify_growth_50k",
        "name": "Tradeify Growth 50K ($0 Activación / EOD)",
        "provider_name": "Tradeify",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / TradingView",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Growth",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 97.0,
        "regular_price_usd": 97.0,
        "promo_price_usd": 58.20,
        "discount_code": "TNT",
        "discount_pct": 40.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "24-48h On-Demand",
        "payout_buffer_usd": 2100.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "6 Minis / 60 Micros",
        "trust_score": 93,
        "stage_type": "EVALUATION",
        "source_url": "https://tradeify.co/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $10k. Cero cuota de activación. Algoritmos permitidos."
    },
    {
        "provider_id": "tradeify_growth_100k",
        "name": "Tradeify Growth 100K ($0 Activación / EOD)",
        "provider_name": "Tradeify",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / TradingView",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 100000.0,
        "program_type": "Growth",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 187.0,
        "regular_price_usd": 187.0,
        "promo_price_usd": 112.20,
        "discount_code": "TNT",
        "discount_pct": 40.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "24-48h On-Demand",
        "payout_buffer_usd": 3100.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "12 Minis / 120 Micros",
        "trust_score": 93,
        "stage_type": "EVALUATION",
        "source_url": "https://tradeify.co/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "$0 activación. Retiros directos vía Rise o Cripto."
    },

    # =========================================================================
    # 4. APEX TRADER FUNDING — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "apex_full_25k",
        "name": "Apex Trader Funding Full 25K",
        "provider_name": "Apex Trader Funding",
        "market_type": "FUTURES",
        "platform": "NinjaTrader 8 / Tradovate / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 25000.0,
        "program_type": "Full Trailing",
        "account_tier": "25K",
        "target_usd": 1500.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 1500.0,
        "max_trailing_dd_pct": 6.0,
        "trailing_dd_type": "Intraday Peak Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PROHIBITED",
        "monthly_cost_usd": 147.0,
        "regular_price_usd": 147.0,
        "promo_price_usd": 29.40,
        "discount_code": "SAVINGS",
        "discount_pct": 80.0,
        "activation_fee_usd": 130.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal (Días 1-5, 15-20)",
        "payout_buffer_usd": 1600.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_PLUS_100",
        "contracts_limit": "4 Minis",
        "trust_score": 88,
        "stage_type": "EVALUATION",
        "source_url": "https://apextraderfunding.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Descuentos agresivos de hasta el 80-90%. Prohibidos bots autónomos (solo traders discrecionales/copiadores)."
    },
    {
        "provider_id": "apex_full_50k",
        "name": "Apex Trader Funding Full 50K",
        "provider_name": "Apex Trader Funding",
        "market_type": "FUTURES",
        "platform": "NinjaTrader 8 / Tradovate / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Full Trailing",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2500.0,
        "max_trailing_dd_pct": 5.0,
        "trailing_dd_type": "Intraday Peak Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PROHIBITED",
        "monthly_cost_usd": 167.0,
        "regular_price_usd": 167.0,
        "promo_price_usd": 33.40,
        "discount_code": "SAVINGS",
        "discount_pct": 80.0,
        "activation_fee_usd": 140.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal (Días 1-5, 15-20)",
        "payout_buffer_usd": 2600.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_PLUS_100",
        "contracts_limit": "10 Minis",
        "trust_score": 88,
        "stage_type": "EVALUATION",
        "source_url": "https://apextraderfunding.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Sin DLL en evaluación. Trailing en vivo persigue ganancias no realizadas hasta +$100 sobre balance inicial."
    },
    {
        "provider_id": "apex_full_100k",
        "name": "Apex Trader Funding Full 100K",
        "provider_name": "Apex Trader Funding",
        "market_type": "FUTURES",
        "platform": "NinjaTrader 8 / Tradovate / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 100000.0,
        "program_type": "Full Trailing",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "Intraday Peak Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PROHIBITED",
        "monthly_cost_usd": 207.0,
        "regular_price_usd": 207.0,
        "promo_price_usd": 41.40,
        "discount_code": "SAVINGS",
        "discount_pct": 80.0,
        "activation_fee_usd": 180.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 3100.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_PLUS_100",
        "contracts_limit": "14 Minis",
        "trust_score": 88,
        "stage_type": "EVALUATION",
        "source_url": "https://apextraderfunding.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Hasta 20 cuentas fondeadas simultáneas con Trade Copier."
    },
    {
        "provider_id": "apex_static_100k",
        "name": "Apex Trader Funding Static 100K (Drawdown Fijo)",
        "provider_name": "Apex Trader Funding",
        "market_type": "FUTURES",
        "platform": "NinjaTrader 8 / Tradovate",
        "allowed_instruments": "MES, MNQ, ES, NQ",
        "account_size": 100000.0,
        "program_type": "Static Drawdown",
        "account_tier": "100K",
        "target_usd": 2000.0,
        "target_pct": 2.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 625.0,
        "max_trailing_dd_pct": 0.625,
        "trailing_dd_type": "Static",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PROHIBITED",
        "monthly_cost_usd": 137.0,
        "regular_price_usd": 137.0,
        "promo_price_usd": 27.40,
        "discount_code": "SAVINGS",
        "discount_pct": 80.0,
        "activation_fee_usd": 140.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 625.0,
        "funded_trailing_lock": "STATIC_NEVER_TRAILS",
        "contracts_limit": "2 Minis / 20 Micros",
        "trust_score": 87,
        "stage_type": "EVALUATION",
        "source_url": "https://apextraderfunding.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "El drawdown es 100% fijo ($99,375). Nunca persigue tus ganancias."
    },

    # =========================================================================
    # 5. TRADEDAY — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "tradeday_50k",
        "name": "TradeDay 50K Day Trader ($0 Activación / Mismo Día)",
        "provider_name": "TradeDay",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / TradingView",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Day Trader",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 1000.0,
        "daily_loss_limit_pct": 2.0,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 5,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 135.0,
        "regular_price_usd": 135.0,
        "promo_price_usd": 59.0,
        "discount_code": "FLASH55",
        "discount_pct": 55.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Mismo día hábil",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "5 Minis / 50 Micros",
        "trust_score": 95,
        "stage_type": "EVALUATION",
        "source_url": "https://www.tradeday.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $10,000 netos. Cero cuota de activación. Pagos el mismo día. Trial de 14 días gratuito."
    },
    {
        "provider_id": "tradeday_100k",
        "name": "TradeDay 100K Day Trader ($0 Activación)",
        "provider_name": "TradeDay",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 100000.0,
        "program_type": "Day Trader",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 2000.0,
        "daily_loss_limit_pct": 2.0,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 3500.0,
        "max_trailing_dd_pct": 3.5,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 5,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 240.0,
        "regular_price_usd": 240.0,
        "promo_price_usd": 108.0,
        "discount_code": "FLASH55",
        "discount_pct": 55.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Mismo día hábil",
        "payout_buffer_usd": 3500.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "10 Minis",
        "trust_score": 95,
        "stage_type": "EVALUATION",
        "source_url": "https://www.tradeday.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $10k. Sin fees ocultos."
    },

    # =========================================================================
    # 6. TAKE PROFIT TRADER — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "takeprofit_25k",
        "name": "Take Profit Trader 25K (Pro Retiros Día 1)",
        "provider_name": "Take Profit Trader",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / TradingView",
        "allowed_instruments": "MES, MNQ, ES, NQ",
        "account_size": 25000.0,
        "program_type": "Pro Test",
        "account_tier": "25K",
        "target_usd": 1500.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 550.0,
        "daily_loss_limit_pct": 2.2,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 1500.0,
        "max_trailing_dd_pct": 6.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 50.0,
        "min_trading_days": 5,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED_WITH_CONDITIONS",
        "monthly_cost_usd": 150.0,
        "regular_price_usd": 150.0,
        "promo_price_usd": 75.0,
        "discount_code": "PRO50",
        "discount_pct": 50.0,
        "activation_fee_usd": 130.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Día 1 en Pro",
        "payout_buffer_usd": 1500.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "3 Minis",
        "trust_score": 90,
        "stage_type": "EVALUATION",
        "source_url": "https://takeprofittrader.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Permite retirar beneficios desde el primer día en cuenta Pro."
    },
    {
        "provider_id": "takeprofit_50k",
        "name": "Take Profit Trader 50K",
        "provider_name": "Take Profit Trader",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / TradingView",
        "allowed_instruments": "MES, MNQ, ES, NQ",
        "account_size": 50000.0,
        "program_type": "Pro Test",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 1100.0,
        "daily_loss_limit_pct": 2.2,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 50.0,
        "min_trading_days": 5,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED_WITH_CONDITIONS",
        "monthly_cost_usd": 170.0,
        "regular_price_usd": 170.0,
        "promo_price_usd": 85.0,
        "discount_code": "PRO50",
        "discount_pct": 50.0,
        "activation_fee_usd": 130.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Día 1 en Pro",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "6 Minis",
        "trust_score": 90,
        "stage_type": "EVALUATION",
        "source_url": "https://takeprofittrader.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Trailing DD frena en $50,000 una vez superado el drawdown."
    },
    {
        "provider_id": "takeprofit_100k",
        "name": "Take Profit Trader 100K",
        "provider_name": "Take Profit Trader",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader",
        "allowed_instruments": "MES, MNQ, ES, NQ",
        "account_size": 100000.0,
        "program_type": "Pro Test",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 2200.0,
        "daily_loss_limit_pct": 2.2,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 50.0,
        "min_trading_days": 5,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED_WITH_CONDITIONS",
        "monthly_cost_usd": 330.0,
        "regular_price_usd": 330.0,
        "promo_price_usd": 165.0,
        "discount_code": "PRO50",
        "discount_pct": 50.0,
        "activation_fee_usd": 130.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Día 1 en Pro",
        "payout_buffer_usd": 3000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "12 Minis",
        "trust_score": 90,
        "stage_type": "EVALUATION",
        "source_url": "https://takeprofittrader.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Sin días de espera para el primer cobro."
    },

    # =========================================================================
    # 7. BULENOX — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "bulenox_50k",
        "name": "Bulenox 50K (Reglas Base)",
        "provider_name": "Bulenox",
        "market_type": "FUTURES",
        "platform": "NinjaTrader / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Standard",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2500.0,
        "max_trailing_dd_pct": 5.0,
        "trailing_dd_type": "Intraday Peak Trailing",
        "consistency_rule_pct": 40.0,
        "min_trading_days": 5,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 175.0,
        "regular_price_usd": 175.0,
        "promo_price_usd": 19.25,
        "discount_code": "GUIDE",
        "discount_pct": 89.0,
        "activation_fee_usd": 148.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 2600.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "7 Minis",
        "trust_score": 75,
        "stage_type": "EVALUATION",
        "source_url": "https://bulenox.com/",
        "verified_at": None,
        "verification_status": "UNVERIFIED",
        "notes": "Plan sin verificar en vivo."
    },
    {
        "provider_id": "bulenox_50k_opt1",
        "name": "Bulenox 50K Opción 1 (Sin Límite Diario)",
        "provider_name": "Bulenox",
        "market_type": "FUTURES",
        "platform": "NinjaTrader / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Opción 1 Trailing",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2500.0,
        "max_trailing_dd_pct": 5.0,
        "trailing_dd_type": "Intraday Peak Trailing",
        "consistency_rule_pct": 40.0,
        "min_trading_days": 5,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 175.0,
        "regular_price_usd": 175.0,
        "promo_price_usd": 19.25,
        "discount_code": "GUIDE",
        "discount_pct": 89.0,
        "activation_fee_usd": 148.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 2600.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "7 Minis",
        "trust_score": 87,
        "stage_type": "EVALUATION",
        "source_url": "https://bulenox.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Descuento del 89% con código permanente. 100% de primeros $10,000 netos."
    },
    {
        "provider_id": "bulenox_100k_opt1",
        "name": "Bulenox 100K Opción 1",
        "provider_name": "Bulenox",
        "market_type": "FUTURES",
        "platform": "NinjaTrader / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 100000.0,
        "program_type": "Opción 1 Trailing",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "Intraday Peak Trailing",
        "consistency_rule_pct": 40.0,
        "min_trading_days": 5,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 215.0,
        "regular_price_usd": 215.0,
        "promo_price_usd": 23.65,
        "discount_code": "GUIDE",
        "discount_pct": 89.0,
        "activation_fee_usd": 178.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 3100.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "12 Minis",
        "trust_score": 87,
        "stage_type": "EVALUATION",
        "source_url": "https://bulenox.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Opción sin pérdida diaria durante examen."
    },

    # =========================================================================
    # 8. FUNDEDNEXT FUTURES — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "fundednext_futures_50k",
        "name": "FundedNext Futures Rapid 50K ($0 Activación)",
        "provider_name": "FundedNext Futures",
        "market_type": "FUTURES",
        "platform": "MT5 / TradeLocker / DXTrade",
        "allowed_instruments": "MES, MNQ, ES, NQ, Commodities",
        "account_size": 50000.0,
        "program_type": "Rapid Futures",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 100.0,
        "min_trading_days": 3,
        "overnight_allowed": True,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 99.0,
        "regular_price_usd": 99.0,
        "promo_price_usd": 99.0,
        "discount_code": None,
        "discount_pct": 0.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "5 Minis",
        "trust_score": 91,
        "stage_type": "EVALUATION",
        "source_url": "https://fundednext.com/general-rules/futures/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Paga 15% de los beneficios obtenidos durante la fase de examen. $0 activación."
    },
    {
        "provider_id": "fundednext_futures_100k",
        "name": "FundedNext Futures Rapid 100K",
        "provider_name": "FundedNext Futures",
        "market_type": "FUTURES",
        "platform": "MT5 / TradeLocker",
        "allowed_instruments": "MES, MNQ, ES, NQ, Commodities",
        "account_size": 100000.0,
        "program_type": "Rapid Futures",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 100.0,
        "min_trading_days": 3,
        "overnight_allowed": True,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 199.0,
        "regular_price_usd": 199.0,
        "promo_price_usd": 199.0,
        "discount_code": None,
        "discount_pct": 0.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 3000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "10 Minis",
        "trust_score": 91,
        "stage_type": "EVALUATION",
        "source_url": "https://fundednext.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "15% profit share en examen. Permite bots de MT5."
    },

    # =========================================================================
    # 9. BLUSKY TRADING — FUTUROS CME (STATIC DRAWDOWN)
    # =========================================================================
    {
        "provider_id": "blusky_static_50k",
        "name": "BluSky Trading Static 50K ($0 Activación / Drawdown Fijo)",
        "provider_name": "BluSky Trading",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Static Growth",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 1000.0,
        "daily_loss_limit_pct": 2.0,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "Static",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 6,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 150.0,
        "regular_price_usd": 150.0,
        "promo_price_usd": 110.0,
        "discount_code": "BLU25",
        "discount_pct": 25.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Semanal / On-Demand",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "STATIC_NEVER_TRAILS",
        "contracts_limit": "4 Minis",
        "trust_score": 92,
        "stage_type": "EVALUATION",
        "source_url": "https://blusky.pro/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Drawdown 100% Estático que nunca se mueve hacia arriba. $0 activación."
    },
    {
        "provider_id": "blusky_static_100k",
        "name": "BluSky Trading Static 100K",
        "provider_name": "BluSky Trading",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 100000.0,
        "program_type": "Static Growth",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 2000.0,
        "daily_loss_limit_pct": 2.0,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "Static",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 6,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 250.0,
        "regular_price_usd": 250.0,
        "promo_price_usd": 187.50,
        "discount_code": "BLU25",
        "discount_pct": 25.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Semanal / On-Demand",
        "payout_buffer_usd": 3000.0,
        "funded_trailing_lock": "STATIC_NEVER_TRAILS",
        "contracts_limit": "8 Minis",
        "trust_score": 92,
        "stage_type": "EVALUATION",
        "source_url": "https://blusky.pro/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Sin trailing drawdown dinámico."
    },

    # =========================================================================
    # 10. TICKTICK TRADER — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "ticktick_50k",
        "name": "TickTick Trader Standard 50K",
        "provider_name": "TickTick Trader",
        "market_type": "FUTURES",
        "platform": "NinjaTrader / Bookmap / Tradovate",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "TTT Standard",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 145.0,
        "regular_price_usd": 145.0,
        "promo_price_usd": 72.50,
        "discount_code": "TTT50",
        "discount_pct": 50.0,
        "activation_fee_usd": 149.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal / On-Demand",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "6 Minis",
        "trust_score": 89,
        "stage_type": "EVALUATION",
        "source_url": "https://tickticktrader.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $25,000 netos. Licencia Bookmap y NinjaTrader gratuita."
    },
    {
        "provider_id": "ticktick_100k",
        "name": "TickTick Trader Standard 100K",
        "provider_name": "TickTick Trader",
        "market_type": "FUTURES",
        "platform": "NinjaTrader / Bookmap / Tradovate",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 100000.0,
        "program_type": "TTT Standard",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 3500.0,
        "max_trailing_dd_pct": 3.5,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 285.0,
        "regular_price_usd": 285.0,
        "promo_price_usd": 142.50,
        "discount_code": "TTT50",
        "discount_pct": 50.0,
        "activation_fee_usd": 149.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal / On-Demand",
        "payout_buffer_usd": 3500.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "12 Minis",
        "trust_score": 89,
        "stage_type": "EVALUATION",
        "source_url": "https://tickticktrader.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $25k."
    },

    # =========================================================================
    # 11. ONEUP TRADER — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "oneup_50k",
        "name": "OneUp Trader 1-Step 50K",
        "provider_name": "OneUp Trader",
        "market_type": "FUTURES",
        "platform": "NinjaTrader / Sierra Chart / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY",
        "account_size": 50000.0,
        "program_type": "1-Step Evaluation",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 1250.0,
        "daily_loss_limit_pct": 2.5,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 2500.0,
        "max_trailing_dd_pct": 5.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 50.0,
        "min_trading_days": 15,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 150.0,
        "regular_price_usd": 150.0,
        "promo_price_usd": 125.0,
        "discount_code": None,
        "discount_pct": 0.0,
        "activation_fee_usd": 75.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 2500.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "6 Minis",
        "trust_score": 90,
        "stage_type": "EVALUATION",
        "source_url": "https://oneuptrader.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $10,000. Data feeds de CME gratuitos incluidos. Requiere 15 días de operativa."
    },

    # =========================================================================
    # 12. FAST TRACK TRADING — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "fasttrack_50k",
        "name": "Fast Track Trading Straight 50K ($0 Activación)",
        "provider_name": "Fast Track Trading",
        "market_type": "FUTURES",
        "platform": "Rithmic / Quantower / NinjaTrader",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY",
        "account_size": 50000.0,
        "program_type": "Direct to Funded",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 149.0,
        "regular_price_usd": 149.0,
        "promo_price_usd": 149.0,
        "discount_code": None,
        "discount_pct": 0.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Semanal",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "5 Minis",
        "trust_score": 88,
        "stage_type": "EVALUATION",
        "source_url": "https://fasttracktrading.net/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Pasa directo a cuenta fondeada. Sin cuota de activación."
    },

    # =========================================================================
    # 13. UPROFIT TRADER — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "uprofit_50k",
        "name": "UProfit Trader Freedom 50K",
        "provider_name": "UProfit Trader",
        "market_type": "FUTURES",
        "platform": "NinjaTrader / RTrader Pro",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Freedom Program",
        "account_tier": "50K",
        "target_usd": 2500.0,
        "target_pct": 5.0,
        "daily_loss_limit_usd": 1100.0,
        "daily_loss_limit_pct": 2.2,
        "dll_calc_model": "Intraday High",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "Intraday Peak Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 4,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 150.0,
        "regular_price_usd": 150.0,
        "promo_price_usd": 89.0,
        "discount_code": "UPROFIT40",
        "discount_pct": 40.0,
        "activation_fee_usd": 150.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "En 24h tras 4 días ganadores",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "6 Minis",
        "trust_score": 89,
        "stage_type": "EVALUATION",
        "source_url": "https://uprofittrader.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $8,000 netos. Target de solo 5% ($2,500). Retiros rápidos tras 4 días."
    },
    {
        "provider_id": "uprofit_100k",
        "name": "UProfit Trader Freedom 100K",
        "provider_name": "UProfit Trader",
        "market_type": "FUTURES",
        "platform": "NinjaTrader / RTrader Pro",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 100000.0,
        "program_type": "Freedom Program",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 2200.0,
        "daily_loss_limit_pct": 2.2,
        "dll_calc_model": "Intraday High",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "Intraday Peak Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 4,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 290.0,
        "regular_price_usd": 290.0,
        "promo_price_usd": 174.0,
        "discount_code": "UPROFIT40",
        "discount_pct": 40.0,
        "activation_fee_usd": 150.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "En 24h tras 4 días ganadores",
        "payout_buffer_usd": 3000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "12 Minis",
        "trust_score": 89,
        "stage_type": "EVALUATION",
        "source_url": "https://uprofittrader.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $8k."
    },

    # =========================================================================
    # 14. ELITE TRADER FUNDING — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "elite_fasttrack_50k",
        "name": "Elite Trader Funding 50K 1-Step Fast Track",
        "provider_name": "Elite Trader Funding",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY",
        "account_size": 50000.0,
        "program_type": "1-Step Fast Track",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 40.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 150.0,
        "regular_price_usd": 150.0,
        "promo_price_usd": 45.0,
        "discount_code": "ETF70",
        "discount_pct": 70.0,
        "activation_fee_usd": 150.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "6 Minis",
        "trust_score": 88,
        "stage_type": "EVALUATION",
        "source_url": "https://elitetraderfunding.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $12,500 netos. Descuentos de hasta el 70% recurrentes."
    },
    {
        "provider_id": "elite_fasttrack_100k",
        "name": "Elite Trader Funding 100K 1-Step",
        "provider_name": "Elite Trader Funding",
        "market_type": "FUTURES",
        "platform": "Tradovate / NinjaTrader / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY",
        "account_size": 100000.0,
        "program_type": "1-Step Fast Track",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 40.0,
        "min_trading_days": 1,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 225.0,
        "regular_price_usd": 225.0,
        "promo_price_usd": 67.50,
        "discount_code": "ETF70",
        "discount_pct": 70.0,
        "activation_fee_usd": 150.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 3000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "12 Minis",
        "trust_score": 88,
        "stage_type": "EVALUATION",
        "source_url": "https://elitetraderfunding.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $12.5k."
    },

    # =========================================================================
    # 15. EARN2TRADE — FUTUROS CME (BROKER REGULADO HELIOS LIVE)
    # =========================================================================
    {
        "provider_id": "earn2trade_tcp_25k",
        "name": "Earn2Trade Trader Career Path 25K ($0 Activación / Live Helios)",
        "provider_name": "Earn2Trade",
        "market_type": "FUTURES",
        "platform": "NinjaTrader 8 / Finamark / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 25000.0,
        "program_type": "Trader Career Path",
        "account_tier": "25K",
        "target_usd": 1750.0,
        "target_pct": 7.0,
        "daily_loss_limit_usd": 550.0,
        "daily_loss_limit_pct": 2.2,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 1500.0,
        "max_trailing_dd_pct": 6.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 10,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED_WITH_CONDITIONS",
        "monthly_cost_usd": 150.0,
        "regular_price_usd": 150.0,
        "promo_price_usd": 120.0,
        "discount_code": "PROMO20",
        "discount_pct": 20.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 80.0,
        "payout_frequency": "Semanal (Helios Live)",
        "payout_buffer_usd": 1500.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "3 Minis",
        "trust_score": 93,
        "stage_type": "EVALUATION",
        "source_url": "https://www.earn2trade.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Escala de $25k a $400k sin pagar exámenes adicionales. Broker institucional regulado Helios Live. Cero cuota de activación."
    },
    {
        "provider_id": "earn2trade_tcp_50k",
        "name": "Earn2Trade Trader Career Path 50K ($0 Activación / Live Helios)",
        "provider_name": "Earn2Trade",
        "market_type": "FUTURES",
        "platform": "NinjaTrader 8 / Finamark / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Trader Career Path",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 1100.0,
        "daily_loss_limit_pct": 2.2,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 10,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED_WITH_CONDITIONS",
        "monthly_cost_usd": 190.0,
        "regular_price_usd": 190.0,
        "promo_price_usd": 152.0,
        "discount_code": "PROMO20",
        "discount_pct": 20.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 80.0,
        "payout_frequency": "Semanal (Helios Live)",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "6 Minis",
        "trust_score": 93,
        "stage_type": "EVALUATION",
        "source_url": "https://www.earn2trade.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Plan de carrera que escala automáticamente a cuenta Live real de $100k, $200k y $400k. $0 activación."
    },

    # =========================================================================
    # 16. LEELOO TRADING — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "leeloo_50k",
        "name": "Leeloo Trading Express 50K",
        "provider_name": "Leeloo Trading",
        "market_type": "FUTURES",
        "platform": "NinjaTrader / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY",
        "account_size": 50000.0,
        "program_type": "Express Combine",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 2500.0,
        "max_trailing_dd_pct": 5.0,
        "trailing_dd_type": "Intraday Peak Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 5,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 150.0,
        "regular_price_usd": 150.0,
        "promo_price_usd": 77.0,
        "discount_code": "LEELOO50",
        "discount_pct": 50.0,
        "activation_fee_usd": 140.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Mensual",
        "payout_buffer_usd": 2600.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "8 Minis",
        "trust_score": 87,
        "stage_type": "EVALUATION",
        "source_url": "https://leelootrading.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $8,000 netos. Algoritmos permitidos."
    },
    {
        "provider_id": "leeloo_100k",
        "name": "Leeloo Trading Express 100K",
        "provider_name": "Leeloo Trading",
        "market_type": "FUTURES",
        "platform": "NinjaTrader / Rithmic",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY",
        "account_size": 100000.0,
        "program_type": "Express Combine",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": None,
        "daily_loss_limit_pct": None,
        "dll_calc_model": "None",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "Intraday Peak Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 5,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 220.0,
        "regular_price_usd": 220.0,
        "promo_price_usd": 110.0,
        "discount_code": "LEELOO50",
        "discount_pct": 50.0,
        "activation_fee_usd": 140.0,
        "payout_split_pct": 90.0,
        "payout_frequency": "Mensual",
        "payout_buffer_usd": 3100.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "12 Minis",
        "trust_score": 87,
        "stage_type": "EVALUATION",
        "source_url": "https://leelootrading.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "100% de primeros $8k."
    },

    # =========================================================================
    # 17. LUCID TRADING / THE TRADING PIT — FUTUROS CME
    # =========================================================================
    {
        "provider_id": "lucid_futures_50k",
        "name": "Lucid Trading Futures 50K ($0 Activación)",
        "provider_name": "Lucid Trading",
        "market_type": "FUTURES",
        "platform": "Quantower / NinjaTrader / VolSys / Bookmap",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 50000.0,
        "program_type": "Executive Futures",
        "account_tier": "50K",
        "target_usd": 3000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 1000.0,
        "daily_loss_limit_pct": 2.0,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 2000.0,
        "max_trailing_dd_pct": 4.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 3,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 169.0,
        "regular_price_usd": 169.0,
        "promo_price_usd": 118.30,
        "discount_code": "LUCID30",
        "discount_pct": 30.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 80.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 2000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "5 Minis",
        "trust_score": 91,
        "stage_type": "EVALUATION",
        "source_url": "https://thetradingpit.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Soporte multi-broker europeo para futuros CME. Licencias Quantower y Bookmap incluidas. Cero cuota de activación."
    },
    {
        "provider_id": "lucid_futures_100k",
        "name": "Lucid Trading Futures 100K ($0 Activación)",
        "provider_name": "Lucid Trading",
        "market_type": "FUTURES",
        "platform": "Quantower / NinjaTrader / VolSys / Bookmap",
        "allowed_instruments": "MES, MNQ, ES, NQ, YM, RTY, CL, GC",
        "account_size": 100000.0,
        "program_type": "Executive Futures",
        "account_tier": "100K",
        "target_usd": 6000.0,
        "target_pct": 6.0,
        "daily_loss_limit_usd": 2000.0,
        "daily_loss_limit_pct": 2.0,
        "dll_calc_model": "EOD Balance",
        "max_trailing_dd_usd": 3000.0,
        "max_trailing_dd_pct": 3.0,
        "trailing_dd_type": "EOD Trailing",
        "consistency_rule_pct": 30.0,
        "min_trading_days": 3,
        "overnight_allowed": False,
        "news_trading_allowed": True,
        "ea_bots_allowed": "PERMITTED",
        "monthly_cost_usd": 299.0,
        "regular_price_usd": 299.0,
        "promo_price_usd": 209.30,
        "discount_code": "LUCID30",
        "discount_pct": 30.0,
        "activation_fee_usd": 0.0,
        "payout_split_pct": 80.0,
        "payout_frequency": "Quincenal",
        "payout_buffer_usd": 3000.0,
        "funded_trailing_lock": "LOCKS_AT_INITIAL_BALANCE",
        "contracts_limit": "10 Minis",
        "trust_score": 91,
        "stage_type": "EVALUATION",
        "source_url": "https://thetradingpit.com/",
        "verified_at": "2026-08-21",
        "verification_status": "VERIFIED",
        "notes": "Firma europea multi-activo de alta gama para futuros CME."
    }
]
